cask "iterm2-beta"
brew "starship"
brew "tmux"
# brew "tldr" # like man
brew "htop"

brew "tree"
brew "ssh-copy-id"
brew "fzf"
brew "exa" # exa like ls
brew "autojump" # j like cd
brew "z" # jumping between various directories easier
# brew "ripgrep"
# brew "jq" # json viewer
# brew "fd"
# brew "bat" # bat like cat
# brew "ranger"
# brew "the_silver_searcher" # ag like ack
# brew "httpie" # like curl
# brew "trash"
# brew "navi" # an interactive cheatsheet tool for the command-line and application launchers

# utils
brew "nmap"
# brew "screenfetch"
# cask "ngrok"

# code - move to code maybe
# brew "go"
# brew "ruby" # beacause of permissions of apple ruby
