eval $(/opt/homebrew/bin/brew shellenv)
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

export PATH="/Users/devall/.local/share/solana/install/active_release/bin:$PATH"
eval "$(pyenv init --path)"
