# ~/.zshrc
. $HOME/.dotfiles/zsh/utils/profiler.start.zsh

export KEYTIMEOUT=1 # Shorter delay typing

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export DOTFILES="$HOME/.dotfiles"

# solana
export PATH="/Users/devall/.local/share/solana/install/active_release/bin:$PATH"

# pip
# export PATH=$PATH:/Users/devall/Library/Python/2.7/bin

# go
# export GOPATH="$HOME/projects/go"
# export PATH=$GOPATH/bin:$PATH

# Rust
# export PATH=$HOME/.cargo/bin:$PATH

# ruby
# export PATH="/usr/local/opt/ruby/bin:$PATH"

# Path to your oh-my-zsh installation.
export ZSH="/Users/devall/.oh-my-zsh"

# ZSH plugins
export ZPLUG_HOME=$(brew --prefix)/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "plugins/git",   from:oh-my-zsh
zplug "zsh-users/zsh-autosuggestions", as:plugin
zplug "dracula/zsh", as:theme

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="dracula"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# . $DOTFILES/zsh/config/oh-my-zsh.zsh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# aliases
. ~/.dotfiles/zsh/config/aliases.zsh

# direnv
eval "$(direnv hook zsh)"

# fnm
eval "$(fnm env)"

# z
. $(brew --prefix)/etc/profile.d/z.sh

# $(brew --prefix)/opt/fzf/install

# starship
eval "$(starship init zsh)"

. $HOME/.dotfiles/zsh/utils/profiler.stop.zsh


eval "$(pyenv init -)"
