# usual
cask "brave-browser"
# cask "google-chrome"
# cask "skype"
cask "slack"
cask "telegram"
# cask "typora"
# cask "termius"
brew "spark"
cask "spotify"
cask "discord"
cask "figma"
cask "notion"

# power
cask "boom-3d"
# cask "bettertouchtool"

# code
cask "jetbrains-toolbox"
cask "docker"
# cask "atom"
# cask "postico"

# utils
cask "obs" # app for streaming
cask "dozer" # better top bar
cask "topnotch" # utility to hide the notch
cask "tunnelblick" # vpn client
# cask "keycastr" # keystroke visualizer
# cask "clean-me"
# cask "caffeinate" # dont find cask
# cask "vnc-viewer"
# cask "dropbox"
# cask "iina"
# cask "transmission"
# cask "keybase"
# cask "postman"
# cask "insomnia"

# cask "rectangle"
# cask "amethyst"
# cask "toggl"
# cask "malwarebytes"
# cask "keka"
# cask "kekadefaultapp"

brew "mas"
mas "Amphetamine", id: 937984704
mas "KeyKey", id: 1035137927

# wanna buy
# https://www.noodlesoft.com/
# !!! https://folivora.ai/
# https://nektony.com/mac-app-cleaner/buy-app-cleaner?app
# https://reederapp.com/
# https://paw.cloud/
# https://www.git-tower.com/pricing/mac
# https://pdfexpert.com/
